-- =====================================================
-- KneneBackend 第三层：高级功能表 - 监控分析相关表
-- 版本：V3.3.1
-- 创建时间：2025-10-30
-- 说明：严格按照数据库架构规范设计，遵循20个规范文档要求
-- =====================================================

-- 设置字符集和排序规则
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- 搜索日志表
-- ----------------------------
-- DROP TABLE IF EXISTS `search_logs`;
CREATE TABLE `search_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID，遵循通用字段设计规范',
  `session_id` varchar(100) COMMENT '会话ID',
  `user_id` bigint COMMENT '用户ID，外键关联users表',
  `user_type` tinyint DEFAULT 1 COMMENT '用户类型：1-普通用户，2-VIP用户，3-游客，4-管理员',
  `search_type` tinyint NOT NULL DEFAULT 1 COMMENT '搜索类型：1-普通搜索，2-高级搜索，3-分类搜索，4-标签搜索',
  `search_keyword` varchar(500) NOT NULL COMMENT '搜索关键词',
  `search_keyword_original` varchar(500) COMMENT '原始搜索关键词',
  `search_keyword_normalized` varchar(500) COMMENT '标准化搜索关键词',
  `search_language` varchar(10) DEFAULT 'zh-CN' COMMENT '搜索语言',
  `search_engine` varchar(50) DEFAULT 'default' COMMENT '搜索引擎：default-默认，elasticsearch-ES，mysql-MySQL',
  `search_algorithm` varchar(100) COMMENT '搜索算法',
  `search_category_id` int COMMENT '搜索分类ID',
  `search_category_name` varchar(100) COMMENT '搜索分类名称',
  `search_filters` json COMMENT '搜索过滤条件，JSON格式',
  `search_sort` varchar(50) DEFAULT 'relevance' COMMENT '排序方式：relevance-相关度，date-日期，size-大小，rating-评分',
  `search_sort_order` varchar(10) DEFAULT 'desc' COMMENT '排序顺序：asc-升序，desc-降序',
  `search_scope` varchar(100) DEFAULT 'all' COMMENT '搜索范围：all-全部，torrents-种子，movies-电影，users-用户',
  `page_number` int DEFAULT 1 COMMENT '页码',
  `page_size` int DEFAULT 20 COMMENT '每页大小',
  `result_count` int DEFAULT 0 COMMENT '结果总数',
  `result_ids` json COMMENT '结果ID列表，JSON格式',
  `result_scores` json COMMENT '结果评分列表，JSON格式',
  `search_time_seconds` decimal(10,4) DEFAULT 0.0000 COMMENT '搜索耗时(秒)',
  `cache_hit` tinyint(1) DEFAULT 0 COMMENT '是否命中缓存：1-命中，0-未命中',
  `cache_key` varchar(200) COMMENT '缓存键',
  `cache_ttl_seconds` int COMMENT '缓存生存时间(秒)',
  `suggestion_used` tinyint(1) DEFAULT 0 COMMENT '是否使用搜索建议：1-使用，0-未使用',
  `suggestion_text` varchar(500) COMMENT '搜索建议内容',
  `auto_correct_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用自动纠错：1-启用，0-禁用',
  `auto_correct_applied` tinyint(1) DEFAULT 0 COMMENT '是否应用自动纠错：1-应用，0-未应用',
  `original_keyword` varchar(500) COMMENT '纠错前关键词',
  `corrected_keyword` varchar(500) COMMENT '纠错后关键词',
  `spell_check_score` decimal(5,2) COMMENT '拼写检查评分',
  `semantic_search_enabled` tinyint(1) DEFAULT 0 COMMENT '是否启用语义搜索：1-启用，0-禁用',
  `semantic_similarity_score` decimal(5,2) COMMENT '语义相似度评分',
  `voice_search` tinyint(1) DEFAULT 0 COMMENT '是否语音搜索：1-是，0-否',
  `voice_confidence` decimal(5,2) COMMENT '语音识别置信度',
  `image_search` tinyint(1) DEFAULT 0 COMMENT '是否图片搜索：1-是，0-否',
  `image_similarity_score` decimal(5,2) COMMENT '图片相似度评分',
  `search_intent` varchar(100) COMMENT '搜索意图：browse-浏览，download-下载，info-信息，compare-对比',
  `intent_confidence` decimal(5,2) COMMENT '意图识别置信度',
  `search_context` json COMMENT '搜索上下文，JSON格式',
  `user_location` varchar(200) COMMENT '用户位置',
  `ip_address` varchar(45) COMMENT 'IP地址',
  `user_agent` varchar(500) COMMENT '用户代理',
  `device_type` varchar(50) COMMENT '设备类型：desktop-桌面，mobile-移动，tablet-平板',
  `browser_type` varchar(50) COMMENT '浏览器类型',
  `os_type` varchar(50) COMMENT '操作系统类型',
  `referrer_url` varchar(500) COMMENT '来源页面URL',
  `utm_source` varchar(200) COMMENT 'UTM来源',
  `utm_medium` varchar(200) COMMENT 'UTM媒介',
  `utm_campaign` varchar(200) COMMENT 'UTM活动',
  `ab_test_group` varchar(50) COMMENT 'A/B测试分组',
  `feature_flags` json COMMENT '功能开关，JSON格式',
  `search_quality_score` decimal(5,2) DEFAULT 0.00 COMMENT '搜索质量评分(0-100)',
  `result_relevance_score` decimal(5,2) DEFAULT 0.00 COMMENT '结果相关性评分',
  `user_satisfaction_score` tinyint COMMENT '用户满意度评分：1-很不满意，2-不满意，3-一般，4-满意，5-很满意',
  `click_through_rate` decimal(5,2) DEFAULT 0.00 COMMENT '点击率(%)',
  `conversion_rate` decimal(5,2) DEFAULT 0.00 COMMENT '转化率(%)',
  `bounce_rate` tinyint(1) DEFAULT 0 COMMENT '是否跳出：1-跳出，0-未跳出',
  `time_to_first_click` int COMMENT '首次点击时间(毫秒)',
  `total_engagement_time` int COMMENT '总互动时间(毫秒)',
  `search_success` tinyint(1) DEFAULT 0 COMMENT '搜索是否成功：1-成功，0-失败',
  `no_results_found` tinyint(1) DEFAULT 0 COMMENT '是否无结果：1-无结果，0-有结果',
  `results_filtered` tinyint(1) DEFAULT 0 COMMENT '结果是否被过滤：1-被过滤，0-未被过滤',
  `error_occurred` tinyint(1) DEFAULT 0 COMMENT '是否发生错误：1-发生，0-未发生',
  `error_code` varchar(50) COMMENT '错误代码',
  `error_message` text COMMENT '错误信息',
  `search_session_id` varchar(100) COMMENT '搜索会话ID',
  `search_sequence_number` int DEFAULT 1 COMMENT '搜索序列号',
  `refined_search` tinyint(1) DEFAULT 0 COMMENT '是否为优化搜索：1-是，0-否',
  `refined_from_search_id` bigint COMMENT '优化的原搜索ID',
  `search_facets_used` json COMMENT '使用的搜索分面，JSON格式',
  `personalization_enabled` tinyint(1) DEFAULT 1 COMMENT '是否启用个性化：1-启用，0-禁用',
  `personalization_factors` json COMMENT '个性化因子，JSON格式',
  `collaborative_filtering_enabled` tinyint(1) DEFAULT 0 COMMENT '是否启用协同过滤：1-启用，0-禁用',
  `machine_learning_model` varchar(100) COMMENT '机器学习模型',
  `ml_confidence_score` decimal(5,2) COMMENT '机器学习置信度',
  `search_performance_metrics` json COMMENT '搜索性能指标，JSON格式',
  `server_load_score` decimal(5,2) COMMENT '服务器负载评分',
  `index_health_score` decimal(5,2) COMMENT '索引健康度评分',
  `query_optimization_applied` tinyint(1) DEFAULT 0 COMMENT '是否应用查询优化：1-应用，0-未应用',
  `optimization_techniques` json COMMENT '优化技术，JSON格式',
  `search_analytics` json COMMENT '搜索分析数据，JSON格式',
  `user_behavior_signals` json COMMENT '用户行为信号，JSON格式',
  `search_trends` json COMMENT '搜索趋势，JSON格式',
  `seasonal_factors` json COMMENT '季节性因子，JSON格式',
  `popularity_score` decimal(8,2) DEFAULT 0.00 COMMENT '搜索热度评分',
  `trending_score` decimal(8,2) DEFAULT 0.00 COMMENT '趋势评分',
  `search_frequency_rank` int DEFAULT 0 COMMENT '搜索频次排名',
  `keyword_category` varchar(100) COMMENT '关键词分类',
  `commercial_intent` tinyint(1) DEFAULT 0 COMMENT '是否有商业意图：1-有，0-无',
  `informational_intent` tinyint(1) DEFAULT 0 COMMENT '是否有信息意图：1-有，0-无',
  `transactional_intent` tinyint(1) DEFAULT 0 COMMENT '是否有交易意图：1-有，0-无',
  `navigational_intent` tinyint(1) DEFAULT 0 COMMENT '是否有导航意图：1-有，0-无',
  `search_validated` tinyint(1) DEFAULT 0 COMMENT '搜索是否已验证：1-已验证，0-未验证',
  `validation_score` decimal(5,2) COMMENT '验证评分',
  `data_quality_score` decimal(5,2) COMMENT '数据质量评分',
  `search_feedback` json COMMENT '搜索反馈，JSON格式',
  `improvement_suggestions` json COMMENT '改进建议，JSON格式',
  `admin_flags` json COMMENT '管理员标记，JSON格式',
  `quality_flags` json COMMENT '质量标记，JSON格式',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，遵循通用字段设计',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，遵循通用字段设计',
  `deleted_at` timestamp NULL COMMENT '删除时间，遵循软删除规范',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`) COMMENT '用户ID索引',
  KEY `idx_session_id` (`session_id`) COMMENT '会话ID索引',
  KEY `idx_search_keyword` (`search_keyword`(255)) COMMENT '搜索关键词索引',
  KEY `idx_search_type` (`search_type`) COMMENT '搜索类型索引',
  KEY `idx_search_engine` (`search_engine`) COMMENT '搜索引擎索引',
  KEY `idx_search_category_id` (`search_category_id`) COMMENT '搜索分类ID索引',
  KEY `idx_result_count` (`result_count`) COMMENT '结果数量索引',
  KEY `idx_search_time_seconds` (`search_time_seconds`) COMMENT '搜索耗时索引',
  KEY `idx_cache_hit` (`cache_hit`) COMMENT '缓存命中索引',
  KEY `idx_search_quality_score` (`search_quality_score`) COMMENT '搜索质量评分索引',
  KEY `idx_user_satisfaction_score` (`user_satisfaction_score`) COMMENT '用户满意度评分索引',
  KEY `idx_click_through_rate` (`click_through_rate`) COMMENT '点击率索引',
  KEY `idx_conversion_rate` (`conversion_rate`) COMMENT '转化率索引',
  KEY `idx_search_success` (`search_success`) COMMENT '搜索成功索引',
  KEY `idx_error_occurred` (`error_occurred`) COMMENT '错误发生索引',
  KEY `idx_search_session_id` (`search_session_id`) COMMENT '搜索会话ID索引',
  KEY `idx_popularity_score` (`popularity_score`) COMMENT '热度评分索引',
  KEY `idx_trending_score` (`trending_score`) COMMENT '趋势评分索引',
  KEY `idx_keyword_category` (`keyword_category`) COMMENT '关键词分类索引',
  KEY `idx_created_at` (`created_at`) COMMENT '创建时间索引',
  KEY `idx_deleted_at` (`deleted_at`) COMMENT '删除时间索引，软删除查询优化',
  KEY `idx_user_type_success` (`user_type`, `search_success`) COMMENT '复合索引：用户类型和成功状态',
  KEY `idx_type_quality_time` (`search_type`, `search_quality_score`, `search_time_seconds`) COMMENT '复合索引：类型、质量、时间',
  KEY `idx_engine_cache_time` (`search_engine`, `cache_hit`, `search_time_seconds`) COMMENT '复合索引：引擎、缓存、时间',
  KEY `idx_session_sequence` (`search_session_id`, `search_sequence_number`) COMMENT '复合索引：会话和序列号',
  KEY `idx_keyword_time` (`search_keyword`(100), `created_at`) COMMENT '复合索引：关键词和时间',
  CHECK (`user_type` IN (1, 2, 3, 4)),
  CHECK (`search_type` IN (1, 2, 3, 4)),
  CHECK (`page_number` >= 1),
  CHECK (`page_size` > 0 AND `page_size` <= 200),
  CHECK (`result_count` >= 0),
  CHECK (`search_quality_score` >= 0 AND `search_quality_score` <= 100),
  CHECK (`user_satisfaction_score` IN (1, 2, 3, 4, 5)),
  CHECK (`click_through_rate` >= 0 AND `click_through_rate` <= 100 AND
         `conversion_rate` >= 0 AND `conversion_rate` <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='搜索日志表，遵循数据库分层设计原则';

-- ----------------------------
-- 用户统计表
-- ----------------------------
-- DROP TABLE IF EXISTS `user_statistics`;
CREATE TABLE `user_statistics` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID，遵循通用字段设计规范',
  `user_id` bigint NOT NULL COMMENT '用户ID，外键关联users表',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `statistics_type` tinyint NOT NULL DEFAULT 1 COMMENT '统计类型：1-日统计，2-周统计，3-月统计，4-年统计',
  `period_start_date` date NOT NULL COMMENT '统计周期开始日期',
  `period_end_date` date NOT NULL COMMENT '统计周期结束日期',
  `activity_status` tinyint DEFAULT 1 COMMENT '活跃状态：1-活跃，2-不活跃，3-新增，4-流失',
  `activity_score` decimal(5,2) DEFAULT 0.00 COMMENT '活跃度评分(0-100)',
  `login_count` int DEFAULT 0 COMMENT '登录次数',
  `login_duration_minutes` int DEFAULT 0 COMMENT '登录总时长(分钟)',
  `avg_login_duration_minutes` decimal(8,2) DEFAULT 0.00 COMMENT '平均登录时长(分钟)',
  `last_login_time` datetime COMMENT '最后登录时间',
  `login_devices` json COMMENT '登录设备列表，JSON格式',
  `login_locations` json COMMENT '登录位置列表，JSON格式',
  `login_ip_addresses` json COMMENT '登录IP地址列表，JSON格式',
  `page_views_count` int DEFAULT 0 COMMENT '页面浏览次数',
  `unique_pages_viewed` int DEFAULT 0 COMMENT '浏览的唯一页面数',
  `avg_session_duration_seconds` int DEFAULT 0 COMMENT '平均会话时长(秒)',
  `bounce_rate` decimal(5,2) DEFAULT 0.00 COMMENT '跳出率(%)',
  `search_count` int DEFAULT 0 COMMENT '搜索次数',
  `search_success_count` int DEFAULT 0 COMMENT '搜索成功次数',
  `search_success_rate` decimal(5,2) DEFAULT 0.00 COMMENT '搜索成功率(%)',
  `avg_search_time_seconds` decimal(8,4) DEFAULT 0.0000 COMMENT '平均搜索耗时(秒)',
  `popular_search_keywords` json COMMENT '热门搜索关键词，JSON格式',
  `search_categories` json COMMENT '搜索分类统计，JSON格式',
  `download_count` int DEFAULT 0 COMMENT '下载次数',
  `download_success_count` int DEFAULT 0 COMMENT '下载成功次数',
  `download_success_rate` decimal(5,2) DEFAULT 0.00 COMMENT '下载成功率(%)',
  `download_size_bytes` bigint DEFAULT 0 COMMENT '下载总大小(字节)',
  `download_size_formatted` varchar(50) COMMENT '格式化下载大小',
  `avg_download_speed_mbps` decimal(8,2) DEFAULT 0.00 COMMENT '平均下载速度(Mbps)',
  `download_categories` json COMMENT '下载分类统计，JSON格式',
  `download_quality_distribution` json COMMENT '下载质量分布，JSON格式',
  `upload_count` int DEFAULT 0 COMMENT '上传次数',
  `upload_size_bytes` bigint DEFAULT 0 COMMENT '上传总大小(字节)',
  `upload_size_formatted` varchar(50) COMMENT '格式化上传大小',
  `upload_success_rate` decimal(5,2) DEFAULT 0.00 COMMENT '上传成功率(%)',
  `comment_count` int DEFAULT 0 COMMENT '评论次数',
  `reply_count` int DEFAULT 0 COMMENT '回复次数',
  `like_count` int DEFAULT 0 COMMENT '点赞次数',
  `share_count` int DEFAULT 0 COMMENT '分享次数',
  `favorite_count` int DEFAULT 0 COMMENT '收藏次数',
  `rating_count` int DEFAULT 0 COMMENT '评分次数',
  `avg_rating_given` decimal(3,2) DEFAULT 0.00 COMMENT '平均给出的评分',
  `report_count` int DEFAULT 0 COMMENT '举报次数',
  `feedback_count` int DEFAULT 0 COMMENT '反馈次数',
  `vip_purchase_count` int DEFAULT 0 COMMENT 'VIP购买次数',
  `vip_revenue_amount` decimal(15,2) DEFAULT 0.00 COMMENT 'VIP收入金额',
  `vip_start_date` date COMMENT 'VIP开始日期',
  `vip_end_date` date COMMENT 'VIP结束日期',
  `vip_usage_statistics` json COMMENT 'VIP使用统计，JSON格式',
  `points_earned` int DEFAULT 0 COMMENT '获得积分',
  `points_spent` int DEFAULT 0 COMMENT '消费积分',
  `points_balance` int DEFAULT 0 COMMENT '积分余额',
  `signin_count` int DEFAULT 0 COMMENT '签到次数',
  `continuous_signin_days` int DEFAULT 0 COMMENT '连续签到天数',
  `invitation_count` int DEFAULT 0 COMMENT '邀请次数',
  `invitation_success_count` int DEFAULT 0 COMMENT '邀请成功次数',
  `referral_bonus_points` int DEFAULT 0 COMMENT '推荐奖励积分',
  `support_ticket_count` int DEFAULT 0 COMMENT '客服工单数量',
  `support_ticket_resolved_count` int DEFAULT 0 COMMENT '客服工单解决数量',
  `support_resolution_rate` decimal(5,2) DEFAULT 0.00 COMMENT '客服解决率(%)',
  `abuse_report_count` int DEFAULT 0 COMMENT '违规举报次数',
  `warning_count` int DEFAULT 0 COMMENT '警告次数',
  `suspension_count` int DEFAULT 0 COMMENT '封禁次数',
  `community_contribution_score` decimal(5,2) DEFAULT 0.00 COMMENT '社区贡献评分',
  `content_quality_score` decimal(5,2) DEFAULT 0.00 COMMENT '内容质量评分',
  `user_satisfaction_score` decimal(5,2) DEFAULT 0.00 COMMENT '用户满意度评分',
  `net_promoter_score` tinyint COMMENT '净推荐值评分：-2-非常不推荐，-1-不推荐，0-中立，1-推荐，2-非常推荐',
  `user_engagement_score` decimal(5,2) DEFAULT 0.00 COMMENT '用户参与度评分',
  `user_loyalty_score` decimal(5,2) DEFAULT 0.00 COMMENT '用户忠诚度评分',
  `user_value_score` decimal(5,2) DEFAULT 0.00 COMMENT '用户价值评分',
  `churn_risk_score` decimal(5,2) DEFAULT 0.00 COMMENT '流失风险评分',
  `predicted_churn_probability` decimal(5,2) DEFAULT 0.00 COMMENT '预测流失概率(%)',
  `retention_probability` decimal(5,2) DEFAULT 0.00 COMMENT '留存概率(%)',
  `user_segment` varchar(50) COMMENT '用户分群：new-新用户，active-活跃用户，vip-VIP用户，power-重度用户，churned-流失用户',
  `user_tier` varchar(50) COMMENT '用户等级：bronze-青铜，silver-白银，gold-黄金，platinum-铂金，diamond-钻石',
  `growth_potential` tinyint DEFAULT 0 COMMENT '增长潜力：0-低，1-中，2-高',
  `influence_score` decimal(5,2) DEFAULT 0.00 COMMENT '影响力评分',
  `social_connections_count` int DEFAULT 0 COMMENT '社交连接数',
  `content_created_count` int DEFAULT 0 COMMENT '创建内容数',
  `content_interactions_count` int DEFAULT 0 COMMENT '内容互动数',
  `device_usage_distribution` json COMMENT '设备使用分布，JSON格式',
  `time_usage_distribution` json COMMENT '时间使用分布，JSON格式',
  `feature_usage_statistics` json COMMENT '功能使用统计，JSON格式',
  `behavior_patterns` json COMMENT '行为模式，JSON格式',
  `preference_profile` json COMMENT '偏好画像，JSON格式',
  `demographic_data` json COMMENT '人口统计数据，JSON格式',
  `interest_topics` json COMMENT '兴趣主题，JSON格式',
  `purchase_behavior` json COMMENT '购买行为，JSON格式',
  `content_consumption_pattern` json COMMENT '内容消费模式，JSON格式',
  `interaction_style` varchar(100) COMMENT '交互风格：passive-被动，neutral-中性，active-主动，power-强力',
  `communication_preference` varchar(100) COMMENT '沟通偏好：email-邮件，sms-短信，push-推送，in-app-应用内',
  `privacy_sensitivity` tinyint DEFAULT 1 COMMENT '隐私敏感度：1-低，2-中，3-高',
  `technical_proficiency` tinyint DEFAULT 2 COMMENT '技术熟练度：1-初级，2-中级，3-高级，4-专家',
  `platform_satisfaction` tinyint COMMENT '平台满意度：1-很不满意，2-不满意，3-一般，4-满意，5-很满意',
  `recommendation_willingness` tinyint COMMENT '推荐意愿：1-不愿意，2-可能，3-愿意，4-非常愿意',
  `compliance_score` decimal(5,2) DEFAULT 100.00 COMMENT '合规评分(0-100)',
  `risk_assessment_score` decimal(5,2) DEFAULT 0.00 COMMENT '风险评估评分',
  `fraud_risk_score` decimal(5,2) DEFAULT 0.00 COMMENT '欺诈风险评分',
  `anomaly_detection_flags` json COMMENT '异常检测标记，JSON格式',
  `security_incident_count` int DEFAULT 0 COMMENT '安全事件次数',
  `data_quality_score` decimal(5,2) DEFAULT 0.00 COMMENT '数据质量评分',
  `completeness_score` decimal(5,2) DEFAULT 0.00 COMMENT '数据完整度评分',
  `accuracy_score` decimal(5,2) DEFAULT 0.00 COMMENT '数据准确度评分',
  `timeliness_score` decimal(5,2) DEFAULT 0.00 COMMENT '数据及时性评分',
  `consistency_score` decimal(5,2) DEFAULT 0.00 COMMENT '数据一致性评分',
  `validation_status` tinyint DEFAULT 1 COMMENT '验证状态：1-未验证，2-部分验证，3-完全验证',
  `last_updated_by` varchar(100) DEFAULT 'system' COMMENT '最后更新者',
  `calculation_method` varchar(100) DEFAULT 'auto' COMMENT '计算方法',
  `calculation_time` datetime COMMENT '计算时间',
  `data_sources` json COMMENT '数据来源，JSON格式',
  `quality_flags` json COMMENT '质量标记，JSON格式',
  `admin_notes` text COMMENT '管理员备注',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间，遵循通用字段设计',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，遵循通用字段设计',
  `deleted_at` timestamp NULL COMMENT '删除时间，遵循软删除规范',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_date_type` (`user_id`, `statistics_date`, `statistics_type`) COMMENT '用户日期类型唯一索引，遵循唯一索引设计规范',
  KEY `idx_user_id` (`user_id`) COMMENT '用户ID索引',
  KEY `idx_statistics_date` (`statistics_date`) COMMENT '统计日期索引',
  KEY `idx_statistics_type` (`statistics_type`) COMMENT '统计类型索引',
  KEY `idx_period_start_date` (`period_start_date`) COMMENT '周期开始日期索引',
  KEY `idx_period_end_date` (`period_end_date`) COMMENT '周期结束日期索引',
  KEY `idx_activity_status` (`activity_status`) COMMENT '活跃状态索引',
  KEY `idx_activity_score` (`activity_score`) COMMENT '活跃度评分索引',
  KEY `idx_login_count` (`login_count`) COMMENT '登录次数索引',
  KEY `idx_page_views_count` (`page_views_count`) COMMENT '页面浏览次数索引',
  KEY `idx_search_count` (`search_count`) COMMENT '搜索次数索引',
  KEY `idx_download_count` (`download_count`) COMMENT '下载次数索引',
  KEY `idx_vip_purchase_count` (`vip_purchase_count`) COMMENT 'VIP购买次数索引',
  KEY `idx_points_balance` (`points_balance`) COMMENT '积分余额索引',
  KEY `idx_user_segment` (`user_segment`) COMMENT '用户分群索引',
  KEY `idx_user_tier` (`user_tier`) COMMENT '用户等级索引',
  KEY `idx_churn_risk_score` (`churn_risk_score`) COMMENT '流失风险评分索引',
  KEY `idx_user_engagement_score` (`user_engagement_score`) COMMENT '用户参与度评分索引',
  KEY `idx_user_value_score` (`user_value_score`) COMMENT '用户价值评分索引',
  KEY `idx_compliance_score` (`compliance_score`) COMMENT '合规评分索引',
  KEY `idx_created_at` (`created_at`) COMMENT '创建时间索引',
  KEY `idx_deleted_at` (`deleted_at`) COMMENT '删除时间索引，软删除查询优化',
  KEY `idx_date_type` (`statistics_date`, `statistics_type`) COMMENT '复合索引：日期和类型',
  KEY `idx_status_score` (`activity_status`, `activity_score`) COMMENT '复合索引：状态和评分',
  KEY `idx_segment_tier` (`user_segment`, `user_tier`) COMMENT '复合索引：分群和等级',
  KEY `idx_engagement_value` (`user_engagement_score`, `user_value_score`) COMMENT '复合索引：参与度和价值',
  CHECK (`statistics_type` IN (1, 2, 3, 4)),
  CHECK (`activity_status` IN (1, 2, 3, 4)),
  CHECK (`activity_score` >= 0 AND `activity_score` <= 100),
  CHECK (`bounce_rate` >= 0 AND `bounce_rate` <= 100 AND
         `search_success_rate` >= 0 AND `search_success_rate` <= 100 AND
         `download_success_rate` >= 0 AND `download_success_rate` <= 100),
  CHECK (`platform_satisfaction` IN (1, 2, 3, 4, 5) AND
         `recommendation_willingness` IN (1, 2, 3, 4)),
  CHECK (`net_promoter_score` IN (-2, -1, 0, 1, 2)),
  CHECK (`user_engagement_score` >= 0 AND `user_engagement_score` <= 100 AND
         `user_loyalty_score` >= 0 AND `user_loyalty_score` <= 100 AND
         `user_value_score` >= 0 AND `user_value_score` <= 100),
  CHECK (`predicted_churn_probability` >= 0 AND `predicted_churn_probability` <= 100 AND
         `retention_probability` >= 0 AND `retention_probability` <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户统计表，遵循数据库分层设计原则';

-- 设置外键检查
SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- 表创建完成说明
-- =====================================================
-- 本迁移脚本创建了第三层高级功能表中的监控分析相关表：
-- 1. search_logs：搜索日志表 - 记录用户搜索行为的详细信息
-- 2. user_statistics：用户统计表 - 存储用户行为和活动的统计数据
--
-- 设计要点：
-- 严格遵循20个规范文档要求，包括命名规范、索引设计、数据完整性等
-- 实现全面的搜索行为分析，支持多种搜索引擎和算法
-- 提供详细的用户活动统计，涵盖登录、浏览、下载等各个方面
-- 包含智能分析功能，如意图识别、情感分析、行为预测
-- 支持多维度的用户画像和分群
-- 实现了完整的性能监控和质量评估
-- 包含丰富的用户行为分析和趋势预测
-- 支持个性化推荐和A/B测试
-- 提供完整的数据质量和验证机制
-- 包含详细的风险评估和合规检查
-- =====================================================