# 生产环境配置
# @author mosctz
# @version 1.0

spring:
  # 数据库配置 - 生产环境
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true&requireSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: false # 生产环境关闭监控页面
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  # Flyway配置 - 生产环境
  flyway:
    enabled: true
    locations: classpath:db/migration/prod
    validate-on-migrate: true
    out-of-order: false

  # Redis配置 - 生产环境
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  # Elasticsearch配置 - 生产环境
  elasticsearch:
    rest:
      uris: ${ES_URIS}
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}
      connection-timeout: 5s
      read-timeout: 30s

  # RocketMQ配置 - 生产环境
  rocketmq:
    name-server: ${ROCKETMQ_NAME_SERVER}
    producer:
      group: knene-producer-group
      send-message-timeout: 5000
      retry-times-when-send-failed: 3
    consumer:
      group: knene-consumer-group
      consume-thread-min: 10
      consume-thread-max: 30

  # MinIO配置 - 生产环境
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: ${MINIO_BUCKET_NAME}
    secure: true

  # 缓存配置 - 生产环境
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30m

  # 生产环境安全配置 - SSL配置已移至server.ssl

# 服务器配置 - 生产环境
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true

# 日志配置 - 生产环境
logging:
  level:
    com.knene: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    com.baomidou.mybatisplus: WARN
    root: WARN
  file:
    name: ${LOG_FILE:/var/log/knene-backend/application.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 监控配置 - 生产环境
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  security:
    enabled: true

# 应用自定义配置 - 生产环境
app:
  # JWT配置 - 生产环境
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:7200} # 2小时

  # 文件存储配置 - 生产环境
  storage:
    local:
      enabled: false
    oss:
      enabled: true
      endpoint: ${OSS_ENDPOINT}
      access-key-id: ${OSS_ACCESS_KEY_ID}
      access-key-secret: ${OSS_ACCESS_KEY_SECRET}
      bucket-name: ${OSS_BUCKET_NAME}

  # 爬虫配置 - 生产环境
  crawler:
    enabled: true
    thread-pool-size: 20
    delay-between-requests: 2000ms
    user-agent: Mozilla/5.0 (compatible; KneneCrawler/1.0)

  # 限流配置 - 生产环境
  rate-limit:
    enabled: true
    default-limit: 60
    window-size: 60s

  # 生产环境特定配置
  prod:
    enable-https: true
    enable-cors: false
    session-timeout: 1800