# 数据库读写分离配置文件
# @author mosctz
# @version 1.0

spring:
  # 主数据源配置（写操作）
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_MASTER_HOST}:${DB_MASTER_PORT}/${DB_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${DB_MASTER_USERNAME}
      password: ${DB_MASTER_PASSWORD}
      druid:
        initial-size: 10
        min-idle: 10
        max-active: 50
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,slf4j

    # 从数据源配置（读操作）
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_SLAVE_HOST}:${DB_SLAVE_PORT}/${DB_NAME}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${DB_SLAVE_USERNAME}
      password: ${DB_SLAVE_PASSWORD}
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 30
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall,slf4j

  # MyBatis配置
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.knene.infrastructure.persistence.entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazy-loading-enabled: true
      aggressive-lazy-loading: false
      multiple-result-sets-enabled: true
      use-column-label: true
      use-generated-keys: false
      auto-mapping-behavior: partial
      default-executor-type: simple
      default-statement-timeout: 30
      default-fetch-size: 100
      safe-row-bounds-enabled: false
      local-cache-scope: session
      jdbc-type-for-null: other
      lazy-load-trigger-methods: equals,clone,hashCode,toString

# 应用自定义配置
app:
  # 读写分离配置
  datasource:
    read-write-splitting:
      enabled: ${DATASOURCE_READ_WRITE_SPLITTING_ENABLED:false}
      load-balance-algorithm: round_robin # round_robin, random, weighted
      master-data-source-name: master
      slave-data-source-names: slave
      # 事务策略
      transaction-strategy: best_effort_delivery # best_effort_delivery, xa

    # 分库分表配置
    sharding:
      enabled: ${DATASOURCE_SHARDING_ENABLED:false}
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds_${user_id % 2}
      default-table-strategy:
        inline:
          sharding-column: id
          algorithm-expression: t_${id % 4}

      # 数据源配置
      datasource:
        names: ds_0,ds_1
        ds_0:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${DB_SHARD_0_HOST}:${DB_SHARD_0_PORT}/${DB_NAME}_0?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: ${DB_SHARD_0_USERNAME}
          password: ${DB_SHARD_0_PASSWORD}
        ds_1:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${DB_SHARD_1_HOST}:${DB_SHARD_1_PORT}/${DB_NAME}_1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: ${DB_SHARD_1_USERNAME}
          password: ${DB_SHARD_1_PASSWORD}

    # 数据库监控配置
    monitor:
      enabled: ${DATASOURCE_MONITOR_ENABLED:true}
      slow-sql-threshold: 1000ms
      log-slow-sql: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ${DRUID_ADMIN_USERNAME:admin}
        login-password: ${DRUID_ADMIN_PASSWORD:admin}
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"