# Spring Security详细配置文件
# @author mosctz
# @version 1.0

# Spring Security配置
spring:
  security:
    # OAuth2配置
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid,profile,email
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            client-name: Google
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope: user:email
            redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/login/oauth2/code/github}
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

    # 密码编码器配置
    password:
      encoder:
        type: bcrypt # bcrypt, pbkdf2, scrypt, argon2
        bcrypt-strength: 12

    # 会话管理配置
    session:
      management:
        session-fixation-protection: migrateSession # migrateSession, newSession, none
        maximum-sessions: 5
        max-sessions-prevents-login: false
        session-registry-alias: sessionRegistry
      timeout: 1800 # 30分钟

    # CSRF配置
    csrf:
      enabled: ${CSRF_ENABLED:true}
      token-repository: http-session
      ignore-ant-patterns:
        - /api/v1/auth/login
        - /api/v1/auth/logout
        - /api/v1/auth/register
        - /swagger-ui/**
        - /v3/api-docs/**

    # CORS配置
    cors:
      enabled: ${CORS_ENABLED:true}
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

    # 记住我配置
    remember-me:
      enabled: ${REMEMBER_ME_ENABLED:true}
      key: ${REMEMBER_ME_KEY:knene-remember-me-key}
      token-validity-seconds: 1209600 # 14天
      remember-me-parameter: remember-me
      remember-me-cookie: remember-me

# 应用自定义安全配置
app:
  security:
    # JWT配置
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: ${JWT_EXPIRATION:86400} # 24小时
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800} # 7天
      issuer: ${JWT_ISSUER:knene-backend}
      audience: ${JWT_AUDIENCE:knene-client}
      header-name: Authorization
      token-prefix: Bearer

    # 密码策略配置
    password-policy:
      enabled: ${PASSWORD_POLICY_ENABLED:true}
      min-length: 8
      max-length: 128
      require-uppercase: true
      require-lowercase: true
      require-digit: true
      require-special-char: true
      forbidden-patterns:
        - password
        - 123456
        - qwerty
        - admin

    # 登录安全配置
    login-security:
      max-attempts: 5
      lockout-duration: 1800 # 30分钟
      attempt-reset-time: 3600 # 1小时
      captcha-enabled: ${LOGIN_CAPTCHA_ENABLED:true}
      captcha-threshold: 3

    # IP白名单配置
    ip-whitelist:
      enabled: ${IP_WHITELIST_ENABLED:false}
      allowed-ips: ${IP_WHITELIST_ALLOWED_IPS:127.0.0.1,::1}
      admin-allowed-ips: ${ADMIN_IP_WHITELIST_ALLOWED_IPS:127.0.0.1,::1}

    # API访问控制配置
    api-access-control:
      enabled: ${API_ACCESS_CONTROL_ENABLED:true}
      public-ant-patterns:
        - /api/v1/auth/**
        - /api/v1/public/**
        - /actuator/health
        - /actuator/info
        - /swagger-ui/**
        - /v3/api-docs/**
      user-ant-patterns:
        - /api/v1/user/**
        - /api/v1/resources/**
        - /api/v1/search/**
      vip-ant-patterns:
        - /api/v1/vip/**
        - /api/v1/download/**
      admin-ant-patterns:
        - /api/v1/admin/**
        - /actuator/**

    # 数据权限配置
    data-permission:
      enabled: ${DATA_PERMISSION_ENABLED:true}
      user-data-isolation: true
      department-data-isolation: false
      tenant-data-isolation: false

    # 审计日志配置
    audit:
      enabled: ${AUDIT_ENABLED:true}
      log-successful-authentications: true
      log-failed-authentications: true
      log-authorization-decisions: true
      exclude-urls:
        - /actuator/health
        - /actuator/info

    # 密钥轮换配置
    key-rotation:
      enabled: ${KEY_ROTATION_ENABLED:false}
      rotation-interval: 2592000 # 30天
      grace-period: 604800 # 7天

    # 多因子认证配置
    mfa:
      enabled: ${MFA_ENABLED:false}
      issuer: ${MFA_ISSUER:Knene}
      secret-length: 32
      code-validity: 30
      backup-codes-count: 10