// 导出业务层组件 - 提供完整的基础视觉元素集合
export { VipBadgeLayer } from './VipBadgeLayer'
export { RatingBadgeLayer } from './RatingBadgeLayer'
export { QualityBadgeLayer } from './QualityBadgeLayer'
export { NewBadgeLayer } from './NewBadgeLayer'
export { HoverInteractionLayer } from './HoverInteractionLayer'
export { CardHoverLayer } from './CardHoverLayer'
export { TextHoverLayer } from './TextHoverLayer'
export { ImageLayer } from './ImageLayer'
export { TitleLayer } from './TitleLayer'
export { MetadataLayer } from './MetadataLayer'
export { MovieLayer } from './MovieLayer'

// 导出类型定义 - 提供完整的TypeScript类型支持
export type { VipBadgeLayerProps } from './VipBadgeLayer'
export type { RatingBadgeLayerProps } from './RatingBadgeLayer'
export type { QualityBadgeLayerProps } from './QualityBadgeLayer'
export type { NewBadgeLayerProps, NewBadgeType } from './NewBadgeLayer'
export type { HoverInteractionLayerProps } from './HoverInteractionLayer'
export type { CardHoverLayerProps } from './CardHoverLayer'
export type { TextHoverLayerProps } from './TextHoverLayer'
export type { ImageLayerProps } from './ImageLayer'
export type { TitleLayerProps } from './TitleLayer'
export type { MetadataLayerProps } from './MetadataLayer'
export type { MovieLayerProps } from './MovieLayer'